# Generated by Django 5.1.1 on 2025-10-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("RoleName", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRoleMap",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("Id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "RoleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.role"
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
