# Generated by Django 5.1.1 on 2025-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_userrolemap"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
