# Generated by Django 5.2.8 on 2025-11-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platfrom',
            new_name='platform',
        ),
    ]
