# Generated by Django 5.1.1 on 2025-10-28 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("PhoneNumber", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
