# Generated by Django 5.1.1 on 2025-10-28 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("propertyapp", "0001_initial"),
        ("users", "0002_role_userrolemap"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCard",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("CustomerClickID", models.BigIntegerField(blank=True, null=True)),
                ("StatusID", models.BigIntegerField(blank=True, null=True)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "PropertieID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="propertyapp.property",
                    ),
                ),
                (
                    "RegionID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="propertyapp.region",
                    ),
                ),
                (
                    "RoleID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
