# Generated by Django 5.1.1 on 2025-10-28 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("RegionName", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("ActiveFlag", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("CreatedBy", models.CharField(blank=True, max_length=50, null=True)),
                ("UpdatedDate", models.DateTimeField(auto_now=True)),
                ("UpdatedBy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("PropertieName", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("ZipCode", models.CharField(max_length=20)),
                ("PropertyType", models.CharField(max_length=50)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("BedRoom", models.IntegerField()),
                ("BathRooms", models.IntegerField()),
                ("SizeInSqft", models.DecimalField(decimal_places=2, max_digits=18)),
                ("IsDisplay", models.BooleanField(default=True)),
                (
                    "RegionID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="propertyapp.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
